#!/bin/bash

SUCC=sugar/tests/success
FAIL=sugar/tests/fail
BIN=erll

echo "== should succeed (0) =="
for i in $(ls $SUCC); do
    FILE=$SUCC/$i
    echo $?: $FILE
    $BIN $FILE > /dev/null
done

echo "== should fail (1) =="
for i in $(ls $FAIL); do
    FILE=$FAIL/$i
    echo $?: $FILE
    $BIN $FILE > /dev/null
done

